services:
  fund_strategies_service:
    build: .
    container_name: fund_strategies_service
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    command: >
      sh -c "python -m uvicorn src.python_cli_starter.main:app --host 0.0.0.0 --port 8000"
    restart: unless-stopped
    # networks:
    #   - shared_app_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


# networks:
#   shared_app_net:
#     external: true
#     name: shared-db-network